# Generated by Django 2.2.6 on 2019-10-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saludo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista_tareas',
            name='realizada',
            field=models.BooleanField(default=False),
        ),
    ]
